### Send POST request with json body
POST https://api.coingate.com/api/v2/orders/52886/checkout
content-type: application/json
authorization: Bearer GaTHXSf1RHAZvgPiuMhe-Sh5Kg9dEBBuDJtGxUwe

{
  "id": 52886,
  "pay_currency": "BTC"
}






