### Send POST request with json body
POST https://api.coingate.com/api/v2/orders/763/checkout
Content-Type: application/json
Authorization: Bearer GaTHXSf1RHAZvgPiuMhe-Sh5Kg9dEBBuDJtGxUwe

{
  "pay_currency": "BTC",
  "id": 763
}






